# --- 开发环境模板，请复制为 application-dev.yml 并填写你自己的信息 ---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    username: your_username
    password: your_password